apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: spring-boot-istio-circuit-breaker-name-destination
spec:
  destination:
    name: spring-boot-istio-circuit-breaker-name
    labels:
      app: spring-boot-istio-circuit-breaker-name
  circuitBreaker:
    simpleCb:
      maxConnections: 100
      httpMaxPendingRequests: 10